### ISSUE TITLE
V4 Tracking

### ISSUE THREAD

**Issue by heff** [muxinc/media-chrome#933]
- [x] Tool tips (https://github.com/muxinc/media-chrome/pull/941)
- [x] Typescript conversion (https://github.com/muxinc/media-chrome/pull/931)
- [x] Redo component imports to be conservative on default bundle size 
	(https://github.com/muxinc/media-chrome/pull/950)
	(https://github.com/muxinc/media-chrome/pull/951)
- [x] include updates from v3 branch
	https://github.com/muxinc/media-chrome/compare/main...3.x
- [x] fix docs menu comp reference section 
	https://www.media-chrome.org/docs/en/components/media-audio-track-menu#reference

**Comment by mmcc** [comment]
Consider making the baobun design our default theme out of the box for Media Chrome.
